[package]
name = "pathfinding-grid"
version = "0.1.0"
authors = ["Jakyle <jjackson360@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rstest = "0.7.0"


[dependencies]
legion = "^0.4.0"
